webcook_cms_security_roles:
    resource: "@WebcookCmsSecurityBundle/Controller/RoleController.php"
    type:     rest

webcook_cms_security_login:
    resource: "@WebcookCmsSecurityBundle/Controller/LoginController.php"
    type:     rest
