services:
    security.access.WebcookCms_voter:
        class: Webcook\Cms\SecurityBundle\Authorization\Voter\WebcookCmsVoter
        arguments:
            - "@doctrine.orm.entity_manager"
        public: false
        tags:
           - { name: security.voter }

    role_controller_event_subscriber:
        class: 'Webcook\Cms\SecurityBundle\EventSubscriber\RoleControllerSubscriber'
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    user_controller_event_subscriber:
        class: 'Webcook\Cms\SecurityBundle\EventSubscriber\UserControllerSubscriber'
        arguments: ["@doctrine.orm.entity_manager", "@security.encoder_factory"]
        tags:
            - { name: kernel.event_subscriber }